name: Main script

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

concurrency:
  group: "script"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Create env variables
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
        run: |
          touch .env
          echo "$ENV_FILE" >> .env

      - name: Run script
        run: |
          npm start
